const pairs = {
  appName: ['Debate IA', 'AI Debate'], tagline: ['Perspectivas diferentes. Uma solução melhor.', 'Different perspectives. A better solution.'], workspace: ['Seu espaço de trabalho', 'Your workspace'], homeTitle: ['Debata. Decida. Construa.', 'Debate. Decide. Build.'], homeDescription: ['Reúna suas IAs para comparar ideias, chegar a um acordo e implementar a solução.', 'Bring your AIs together to compare ideas, reach an agreement, and implement the solution.'],
  debates: ['Seus debates', 'Your debates'], newDebate: ['Novo debate', 'New debate'], backToDebate: ['Voltar ao debate', 'Back to debate'], open: ['Abrir conversa', 'Open conversation'], history: ['Todos os debates', 'All debates'],
  settings: ['Configurações', 'Settings'], language: ['Idioma', 'Language'], system: ['Sistema', 'System'], portuguese: ['Português', 'Português'], english: ['English', 'English'], languageHelp: ['A interface e os próximos prompts seguem este idioma. Mensagens já enviadas são preservadas.', 'The interface and future prompts follow this language. Existing messages are preserved.'],
  sound: ['Som de novas mensagens', 'New message sound'], soundHelp: ['Um toque suave quando qualquer IA enviar uma mensagem, mesmo fora do chat.', 'A gentle tone whenever any AI sends a message, even outside the chat.'], testSound: ['Testar som', 'Test sound'], soundOn: ['Som ligado', 'Sound on'], soundOff: ['Som desligado', 'Sound off'], soundBlocked: ['Clique em Testar som para ativar o áudio.', 'Click Test sound to enable audio.'],
  live: ['Ao vivo', 'Live'], offline: ['Reconectando…', 'Reconnecting…'], connecting: ['Conectando…', 'Connecting…'], synced: ['Atualizações em tempo real', 'Updates in real time'], loading: ['Carregando seus debates…', 'Loading your debates…'],
  emptyTitle: ['Boas soluções começam com boas perguntas.', 'Good solutions start with good questions.'], emptyBody: ['Reúna suas IAs, apresente um problema e acompanhe a conversa até chegarem a uma solução.', 'Bring your AIs together, share a problem, and follow their conversation until they reach a solution.'], firstDebate: ['Criar primeiro debate', 'Create first debate'],
  openState: ['Em andamento', 'In progress'], agreedState: ['Escrevendo solução', 'Writing solution'], closedState: ['Encerrado', 'Completed'], draft: ['Preparação', 'Preparing'],
  messages: ['mensagens', 'messages'], round: ['Rodada', 'Round'], proposal: ['Proposta', 'Proposal'], unanimous: ['Unanimidade', 'Unanimous'], forced: ['Sem unanimidade', 'Without unanimity'], waitingFor: ['Falta o apoio de', 'Awaiting support from'], implements: ['Implementa', 'Implementer'], supports: ['Apoia a proposta', 'Supports proposal'],
  turnOf: ['Vez de', 'Turn:'], elapsed: ['há', 'for'], writing: ['Escrevendo a solução', 'Writing the solution'], thinking: ['Elaborando a próxima resposta', 'Preparing the next response'], running: ['O debate continua em andamento', 'The debate is still running'], runningHelp: ['Você pode navegar e voltar quando quiser.', 'Explore the app and come back whenever you like.'],
  rename: ['Renomear', 'Rename'], delete: ['Excluir', 'Delete'], cancel: ['Cancelar', 'Cancel'], save: ['Salvar', 'Save'], close: ['Fechar', 'Close'], confirm: ['Confirmar', 'Confirm'], copied: ['Copiado', 'Copied'], copy: ['Copiar', 'Copy'], saved: ['Alterações salvas', 'Changes saved'],
  deleteTitle: ['Excluir debate', 'Delete debate'], deleteBody: ['O debate e todas as suas mensagens serão apagados. Esta ação não pode ser desfeita.', 'The debate and all its messages will be deleted. This cannot be undone.'], renameTitle: ['Renomear debate', 'Rename debate'],
  agents: ['Agentes', 'Agents'], topic: ['Assunto', 'Topic'], prompts: ['Prompts', 'Prompts'], step: ['Passo', 'Step'], of: ['de', 'of'], next: ['Avançar', 'Next'], back: ['Voltar', 'Back'],
  topicTitle: ['Sobre o que elas vão debater?', 'What should they debate?'], topicHelp: ['Descreva o problema, as evidências e o resultado esperado.', 'Describe the problem, the evidence, and the expected result.'], title: ['Título', 'Title'], titlePlaceholder: ['Ex.: O sorteio aleatório não finaliza', 'E.g. The random draw never finishes'], topicPlaceholder: ['O que acontece?\nComo reproduzir?\nQuais arquivos estão envolvidos?\nComo verificar que o problema foi resolvido?', 'What happens?\nHow can it be reproduced?\nWhich files are involved?\nHow can the fix be verified?'], projectTip: ['Abra cada IA na pasta do projeto para que todas consultem o mesmo código.', 'Open each AI in the project directory so they can all inspect the same code.'], topicMinimum: ['Descreva o assunto em pelo menos 20 caracteres.', 'Describe the topic in at least 20 characters.'],
  agentsTitle: ['Quem participa da conversa?', 'Who joins the conversation?'], agentsHelp: ['A primeira IA propõe uma solução. As outras questionam e contribuem. Adicione pelo menos duas.', 'The first AI proposes a solution. The others challenge it and contribute. Add at least two.'], addAI: ['Adicionar IA', 'Add AI'], add: ['Adicionar', 'Add'], otherAI: ['Outra IA', 'Other AI'], name: ['Nome', 'Name'], role: ['Papel', 'Role'], optionalRole: ['Papel opcional', 'Optional role'], proposer: ['Abre o debate', 'Opens the debate'], critic: ['Crítico', 'Critic'], noAgents: ['Escolha uma IA para começar.', 'Choose an AI to get started.'], editRole: ['Editar papel', 'Edit role'], remove: ['Remover', 'Remove'], roleHelp: ['Este papel será incluído no prompt da IA.', 'This role will be included in the AI’s prompt.'],
  promptsHelp: ['Cole o prompt de cada IA no terminal dela, aberto na pasta do projeto. Todas precisam enviar a confirmação de presença para liberar o chat.', 'Paste each AI’s prompt into its terminal, opened in the project directory. Every AI must send attendance confirmation to unlock the chat.'], copyPrompt: ['Copiar prompt', 'Copy prompt'], connectHelp: ['Como conectar', 'How to connect'], codexHelp: ['No Codex, permita acesso à rede local nas configurações de execução.', 'In Codex, allow local network access in the execution settings.'], claudeHelp: ['No Claude Code, permita os comandos curl para as consultas ao servidor.', 'In Claude Code, allow curl commands to query the server.'], server: ['Servidor', 'Server'],
  controls: ['Controles do debate', 'Debate controls'], maxRounds: ['Rodadas máximas', 'Maximum rounds'], skip: ['Passar a vez', 'Skip turn'], decide: ['Forçar decisão', 'Force decision'], stop: ['Encerrar debate', 'End debate'], stopTitle: ['Encerrar debate', 'End debate'], stopBody: ['Encerra a conversa das IAs. Você pode registrar uma solução final opcional.', 'Ends the AI conversation. You may provide an optional final solution.'], finalPlaceholder: ['Solução final (opcional)', 'Final solution (optional)'], decideBody: ['Adota a proposta com mais apoio e pede ao responsável que escreva a solução final.', 'Adopts the proposal with the most support and asks its writer to deliver the final solution.'], newToken: ['Gerar novo token', 'Generate new token'], newTokenBody: ['O prompt anterior deixa de funcionar. Copie o novo prompt para reconectar esta IA.', 'The previous prompt will stop working. Copy the new prompt to reconnect this AI.'],
  moderator: ['Moderador', 'Moderator'], systemAuthor: ['Sistema', 'System'], to: ['Para', 'To'], everyone: ['Todos', 'Everyone'], send: ['Enviar', 'Send'], hint: ['Dica', 'Hint'], hintPlaceholder: ['Envie uma dica sem interromper a vez das IAs…', 'Share a hint without interrupting the AIs’ turns…'], hintHelp: ['Enter envia · Shift + Enter quebra a linha', 'Enter to send · Shift + Enter for a new line'], closedHelp: ['Debate encerrado. A solução e as mensagens ficam salvas aqui.', 'Debate completed. The solution and messages are saved here.'],
  noMessages: ['Aguardando a primeira mensagem', 'Waiting for the first message'], noMessagesHelp: ['Cole os prompts nas IAs. As respostas aparecem aqui automaticamente.', 'Paste the prompts into the AIs. Their replies will appear here automatically.'], proposed: ['Proposta', 'Proposal'], agreedWith: ['Apoia', 'Supports'], passed: ['Passou a vez', 'Passed turn'], finalText: ['Texto final', 'Final text'], finalSolution: ['Solução final', 'Final solution'], writtenBy: ['Escrita por', 'Written by'], noAgreement: ['Encerrado pelo moderador', 'Ended by the moderator'], finalSaved: ['Solução salva com o histórico do debate.', 'Solution saved with the debate history.'],
  newMessages: ['Novas mensagens', 'New messages'], connectionError: ['Não foi possível conectar ao servidor.', 'Unable to connect to the server.'], requestError: ['Não foi possível concluir a ação.', 'Unable to complete this action.'], badAdmin: ['Recarregue a página para renovar o acesso de moderador.', 'Reload the page to refresh moderator access.'], copyError: ['Não foi possível copiar. Abra o prompt e copie o texto.', 'Unable to copy. Open the prompt and copy its text.'], notFound: ['Este debate não está mais disponível.', 'This debate is no longer available.'], invalidRounds: ['Informe um número inteiro entre 2 e 50.', 'Enter a whole number between 2 and 50.'], languageSaved: ['Idioma atualizado', 'Language updated'], liveCount: ['em andamento', 'in progress'], noTopic: ['Sem assunto definido', 'No topic set'], participants: ['participantes', 'participants'], noProposal: ['Aguardando uma proposta', 'Waiting for a proposal'], viewSolution: ['Ver solução', 'View solution'], unsaved: ['Não salvo', 'Unsaved'], promptLanguage: ['Idioma do prompt', 'Prompt language'], selectRecipient: ['Destinatário da dica', 'Hint recipient']
};

Object.assign(pairs, {
  implementation: ['Implementação', 'Implementation'], implementationHelp: ['Defina quem implementa a solução assim que o debate terminar.', 'Choose who implements the solution as soon as the debate ends.'], chooseAtEnd: ['Escolher ao final', 'Choose at the end'], proposalAgent: ['IA indicada na proposta', 'AI named in the proposal'], specificAgent: ['Escolher uma IA', 'Choose an AI'], noImplementation: ['Não implementar automaticamente', 'Do not implement automatically'], implementer: ['IA que vai implementar', 'Implementation agent'], unanimousOnly: ['Implementar somente com unanimidade', 'Implement only with unanimity'], anyDecision: ['Vale para decisões unânimes ou sem unanimidade.', 'Applies to unanimous and non-unanimous decisions.'], implementNow: ['Implementar agora', 'Implement now'], awaitingImplementer: ['Solução pronta. Escolha quem vai implementar.', 'Solution ready. Choose who will implement it.'], implementationAssigned: ['Implementação encaminhada para', 'Implementation assigned to'], implementationAssignedHelp: ['A IA recebeu a instrução para implementar na próxima consulta ao servidor.', 'The AI will receive the implementation instruction on its next server request.'], implementationSkipped: ['Implementação automática desativada.', 'Automatic implementation is disabled.'], implementationNoConsensus: ['A implementação aguarda uma decisão unânime.', 'Implementation requires a unanimous decision.'], implementationNoSolution: ['Nenhuma proposta foi adotada para implementar.', 'No proposal was adopted for implementation.'], implementationSaved: ['Configuração de implementação salva', 'Implementation settings saved'], selectAI: ['Selecionar IA', 'Select AI'], implementationManualHelp: ['As IAs aguardam sua escolha. A implementação começa quando você confirmar.', 'The AIs wait for your choice. Implementation starts when you confirm.']
});



Object.assign(pairs, {
  proposalAgent: ['Deixar as IAs decidirem', 'Let the AIs decide'], reviewAfter: ['Revisar após implementar', 'Review after implementation'], reviewAfterHelp: ['A responsável deve relatar mudanças, arquivos e verificações. As outras IAs revisam até aprovar o resultado ou acordar novos ajustes.', 'The implementer must report changes, files, and verification. The other AIs review until they approve the result or agree on further changes.'], reviewPhase: ['Revisão da implementação', 'Implementation review'], reviewCycle: ['Ciclo de revisão', 'Review cycle'], reviewReport: ['Relatório de implementação', 'Implementation report'], reviewComplete: ['Implementação aprovada pelas IAs', 'Implementation approved by the AIs'], reviewWaiting: ['Aguardando o relatório da implementação', 'Waiting for the implementation report'], reviewWaitingHelp: ['A IA responsável deve voltar com o que fez, os arquivos alterados e as verificações. As demais aguardam para revisar.', 'The implementer must return with the changes, modified files, and verification. The other AIs are waiting to review.'], implementationChoice: ['Escolher implementador', 'Choose implementer'], reviewChanges: ['Novos ajustes acordados', 'Further changes agreed'], automaticChoiceHelp: ['Sem escolha manual, as IAs definem o responsável na proposta acordada.', 'Without a manual choice, the AIs nominate the implementer in their agreed proposal.']
});

Object.assign(pairs, {
  presence: ['Presença', 'Attendance'], presenceConfirmed: ['Presença confirmada', 'Attendance confirmed'], presencePending: ['Aguardando confirmação', 'Awaiting confirmation'], waitingForAgents: ['Aguardando as IAs', 'Waiting for the AIs'], presenceCount: ['presenças confirmadas', 'attendance confirmations'], presenceHelp: ['Copie o prompt e envie para cada IA na pasta do projeto. Cada uma precisa executar o comando de liberação incluído nele. Copiar o prompt não confirma presença.', 'Copy the prompt to each AI in the project directory. Each one must run the release command included in its prompt. Copying the prompt does not confirm attendance.'], allPresent: ['Todas as IAs confirmaram presença', 'Every AI has confirmed attendance'], readinessTitle: ['Aguardando a liberação das IAs', 'Waiting for the AIs to release the chat'], readinessLocked: ['O chat abre automaticamente quando todas confirmarem. Até lá, as IAs não podem enviar mensagens.', 'The chat opens automatically once everyone confirms. Until then, the AIs cannot send messages.'], openReadiness: ['Ver confirmações', 'View confirmations'], waitingForRelease: ['Aguardando liberação de:', 'Waiting for release from:']
});

Object.assign(pairs, {
  readinessNeedsAgents: ['Adicione pelo menos duas IAs para começar a confirmar presença.', 'Add at least two AIs to complete attendance confirmation.'], awaitingTurn: ['Aguardando a vez', 'Waiting for its turn'], roundsHelp: ['Cada mensagem passa a vez. O limite de rodadas vale para o debate inteiro.', 'Each message passes the turn. The round limit applies to the entire debate.'], copyError: ['Não foi possível copiar. Permita o acesso à área de transferência e tente novamente.', 'Unable to copy. Allow clipboard access and try again.'], requiredField: ['Preencha este campo.', 'This field is required.']
});

Object.assign(pairs, {
  cardConversation: ['Conversa', 'Conversation'], cardActivity: ['Agora no debate', 'Now in the debate'], cardAgents: ['IAs conectadas', 'connected AIs'], lastMessage: ['Última mensagem', 'Last message'], acceptance: ['Aceitação', 'Acceptance'], noAcceptance: ['Ainda não apoiou uma proposta', 'No proposal supported yet'], previousAcceptance: ['Apoio a uma proposta anterior', 'Support for a previous proposal'], activityDetails: ['Ver atividade de', 'View activity for'], noAgentMessage: ['Ainda não enviou mensagens', 'No messages yet'], ago: ['há', 'ago'],
  cite: ['Citar com @', 'Cite with @'], citeAnything: ['Citar uma IA, mensagem ou assunto', 'Cite an AI, message, or topic'], citeHelp: ['↑ ↓ navega · Enter cita · Esc fecha', '↑ ↓ navigate · Enter cites · Esc closes'], noReferences: ['Nenhuma referência encontrada', 'No matching references'], referenceLimit: ['Use até 12 referências por mensagem.', 'Use up to 12 references per message.'], referenceSnapshot: ['Conteúdo no momento do envio', 'Content at the time of sending'], referenceTruncated: ['Trecho inicial da referência', 'Beginning of the referenced content'],
  hintPlaceholder: ['Escreva uma mensagem… use @ para citar', 'Write a message… use @ to cite'], hintHelp: ['Enter envia · Shift + Enter nova linha', 'Enter to send · Shift + Enter new line']
});

export const messages = Object.fromEntries(['pt', 'en'].map((locale, i) => [locale, Object.fromEntries(Object.entries(pairs).map(([key, values]) => [key, values[i]]))]));

export function systemLanguage() {
  return (navigator.languages?.[0] || navigator.language || 'en').toLowerCase().startsWith('pt') ? 'pt' : 'en';
}

export function resolveLanguage(preference) {
  return preference === 'pt' || preference === 'en' ? preference : systemLanguage();
}
